# Risk Insurance Evaluation - Wagner Brito

In [2]:
import pandas as pd

In [3]:
# Load dataset
insurance = pd.read_csv('insurance.csv',index_col=0)

## First impressions about this dataset

In [4]:
insurance.head()

GoodStudent         Age    SocioEcon RiskAversion VehicleYear ThisCarDam  \
1        False       Adult        Prole  Adventurous       Older   Moderate   
2        False      Senior        Prole     Cautious     Current       None   
3        False      Senior  UpperMiddle   Psychopath     Current       None   
4        False  Adolescent       Middle       Normal       Older       None   
5        False  Adolescent        Prole       Normal       Older   Moderate   

  RuggedAuto  Accident    MakeModel DrivQuality  ... HomeBase  AntiTheft  \
1   EggShell      Mild      Economy        Poor  ...     City      False   
2   Football      None      Economy      Normal  ...     City       True   
3   Football      None  FamilySedan   Excellent  ...     City      False   
4   EggShell      None      Economy      Normal  ...   Suburb      False   
5   Football  Moderate      Economy        Poor  ...     City      False   

   PropCost  OtherCarCost OtherCar   MedCost Cushioning Airbag   ILiCost  \
1   TenThou      Thousand     True  Thousand       Poor  False  Thousand   
2  Thousand      Thousand     True  Thousand       Good   True  Thousand   
3  Thousand      Thousand    False  Thousand       Good   True  Thousand   
4  Thousand      Thousand     True  Thousand       Fair  False  Thousand   
5   TenThou      Thousand    False  Thousand       Fair  False  Thousand   

  DrivHist  
1     Many  
2     Zero  
3      One  
4     Zero  
5     Many  

[5 rows x 27 columns]

### Aparently I don't need worry about missing data

In [5]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 1 to 20000
Data columns (total 27 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   GoodStudent   20000 non-null  bool  
 1   Age           20000 non-null  object
 2   SocioEcon     20000 non-null  object
 3   RiskAversion  20000 non-null  object
 4   VehicleYear   20000 non-null  object
 5   ThisCarDam    20000 non-null  object
 6   RuggedAuto    20000 non-null  object
 7   Accident      20000 non-null  object
 8   MakeModel     20000 non-null  object
 9   DrivQuality   20000 non-null  object
 10  Mileage       20000 non-null  object
 11  Antilock      20000 non-null  bool  
 12  DrivingSkill  20000 non-null  object
 13  SeniorTrain   20000 non-null  bool  
 14  ThisCarCost   20000 non-null  object
 15  Theft         20000 non-null  bool  
 16  CarValue      20000 non-null  object
 17  HomeBase      20000 non-null  object
 18  AntiTheft     20000 non-null  bool  
 19  Prop

In [6]:
'''
Some points:
Age: Adult = 11939
AntiTheft: False = 11705
'''
insurance.describe()

GoodStudent    Age SocioEcon RiskAversion VehicleYear ThisCarDam  \
count        20000  20000     20000        20000       20000      20000   
unique           2      3         4            4           2          4   
top          False  Adult     Prole       Normal       Older       None   
freq         19115  11939      8444         9644       13089      14681   

       RuggedAuto Accident MakeModel DrivQuality  ... HomeBase AntiTheft  \
count       20000    20000     20000       20000  ...    20000     20000   
unique          3        4         5           3  ...        4         2   
top      EggShell     None   Economy      Normal  ...     City     False   
freq         9838    14336      7637        8897  ...     7709     11705   

        PropCost OtherCarCost OtherCar   MedCost Cushioning Airbag   ILiCost  \
count      20000        20000    20000     20000      20000  20000     20000   
unique         4            3        2         4          4      2         4   
top     Thousand     Thousand     True  Thousand       Poor  False  Thousand   
freq       11170        17180    13955     18589       6547  11468     19356   

       DrivHist  
count     20000  
unique        3  
top        Zero  
freq      11486  

[4 rows x 27 columns]

In [26]:
insurance.iloc[:,0:9].describe()

GoodStudent    Age SocioEcon RiskAversion VehicleYear ThisCarDam  \
count        20000  20000     20000        20000       20000      20000   
unique           2      3         4            4           2          4   
top          False  Adult     Prole       Normal       Older       None   
freq         19115  11939      8444         9644       13089      14681   

       RuggedAuto Accident MakeModel  
count       20000    20000     20000  
unique          3        4         5  
top      EggShell     None   Economy  
freq         9838    14336      7637

In [27]:
insurance.iloc[:,9:18].describe()

DrivQuality    Mileage Antilock DrivingSkill SeniorTrain ThisCarCost  \
count        20000      20000    20000        20000       20000       20000   
unique           3          4        2            3           2           4   
top         Normal  FiftyThou    False       Normal       False    Thousand   
freq          8897       8041    16041        11308       17665       16443   

        Theft  CarValue HomeBase  
count   20000     20000    20000  
unique      2         5        4  
top     False  FiveThou     City  
freq    19969      8467     7709

In [28]:
insurance.iloc[:,18:].describe()

AntiTheft  PropCost OtherCarCost OtherCar   MedCost Cushioning Airbag  \
count      20000     20000        20000    20000     20000      20000  20000   
unique         2         4            3        2         4          4      2   
top        False  Thousand     Thousand     True  Thousand       Poor  False   
freq       11705     11170        17180    13955     18589       6547  11468   

         ILiCost DrivHist  
count      20000    20000  
unique         4        3  
top     Thousand     Zero  
freq       19356    11486

## This is the object of this study
### Create a model to classified a accident severity level

In [7]:
'''
Accident severity level:
    'Mild':'Not severe'
    'None',:'Don't have any accident'
    'Moderate':'Moderate'
    'Severe':'Severe'
'''
insurance['Accident'].unique()

array(['Mild', 'None', 'Moderate', 'Severe'], dtype=object)

### Watching a percentage of accident severity level in hole dataset

In [19]:
df_accident = insurance.groupby('Accident').count()['Age']
df_accident = pd.DataFrame(df_accident)
df_accident.columns = ['Total']
df_accident['%'] = (df_accident / 20000) * 100
df_accident

Total      %
Accident              
Mild       1738   8.69
Moderate   1604   8.02
None      14336  71.68
Severe     2322  11.61

### Looking the values of attributes

In [12]:
for c_name in insurance.columns:
    print(c_name,": ",insurance[c_name].unique())

GoodStudent :  [False  True]
Age :  ['Adult' 'Senior' 'Adolescent']
SocioEcon :  ['Prole' 'UpperMiddle' 'Middle' 'Wealthy']
RiskAversion :  ['Adventurous' 'Cautious' 'Psychopath' 'Normal']
VehicleYear :  ['Older' 'Current']
ThisCarDam :  ['Moderate' 'None' 'Mild' 'Severe']
RuggedAuto :  ['EggShell' 'Football' 'Tank']
Accident :  ['Mild' 'None' 'Moderate' 'Severe']
MakeModel :  ['Economy' 'FamilySedan' 'SportsCar' 'Luxury' 'SuperLuxury']
DrivQuality :  ['Poor' 'Normal' 'Excellent']
Mileage :  ['TwentyThou' 'Domino' 'FiftyThou' 'FiveThou']
Antilock :  [False  True]
DrivingSkill :  ['SubStandard' 'Normal' 'Expert']
SeniorTrain :  [False  True]
ThisCarCost :  ['TenThou' 'Thousand' 'HundredThou' 'Million']
Theft :  [False  True]
CarValue :  ['FiveThou' 'TenThou' 'TwentyThou' 'FiftyThou' 'Million']
HomeBase :  ['City' 'Suburb' 'Secure' 'Rural']
AntiTheft :  [False  True]
PropCost :  ['TenThou' 'Thousand' 'HundredThou' 'Million']
OtherCarCost :  ['Thousand' 'HundredThou' 'TenThou']
OtherCar :

### Try run a Random Forest with this attributes
#### Age RiskAversion DrivQuality DrivingSkill HomeBase DrivHist

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [6]:
previsores = insurance[['Age','RiskAversion','DrivQuality','DrivingSkill','HomeBase','DrivHist']].values
classe = insurance['Accident'].values

### Parse categorical data to numerical

In [8]:
labelencoder = LabelEncoder()
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])
previsores[:, 2] = labelencoder.fit_transform(previsores[:, 2])
previsores[:, 3] = labelencoder.fit_transform(previsores[:, 3])
previsores[:, 4] = labelencoder.fit_transform(previsores[:, 4])
previsores[:, 5] = labelencoder.fit_transform(previsores[:, 5])

### Slipt data to train and test

In [14]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

### Creating model

In [15]:
floresta = RandomForestClassifier(n_estimators = 100)
floresta.fit(X_treinamento, y_treinamento)

RandomForestClassifier()

In [16]:
previsoes = floresta.predict(X_teste)
confusao = confusion_matrix(y_teste, previsoes)
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.7096666666666667

### Evaluate all attributes to trying to increase the hit hate

In [5]:
previsores_2 = insurance[['GoodStudent', 'Age', 'SocioEcon',\
                          'RiskAversion', 'VehicleYear', 'ThisCarDam',\
                          'RuggedAuto', 'MakeModel', 'DrivQuality',\
                          'Mileage', 'Antilock', 'DrivingSkill',\
                          'SeniorTrain', 'ThisCarCost', 'Theft',\
                          'CarValue', 'HomeBase', 'AntiTheft',\
                          'PropCost', 'OtherCarCost', 'OtherCar',\
                          'MedCost', 'Cushioning', 'Airbag', 'ILiCost','DrivHist']].values

In [9]:
for i in range(previsores_2.shape[1]):
    previsores_2[:,i] = labelencoder.fit_transform(previsores_2[:,i])

In [10]:
X_treinamento_2, X_teste_2, y_treinamento_2, y_teste_2 = train_test_split(previsores_2,\
                                                                          classe,\
                                                                          test_size = 0.3,\
                                                                          random_state = 1)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [41]:
forest = ExtraTreesClassifier()
forest.fit(X_treinamento_2, y_treinamento_2)
importancias = forest.feature_importances_
importancias

array([0.03826341, 0.03050124, 0.04909587, 0.03810542, 0.02444953,
       0.03353926, 0.02556499, 0.02595993, 0.06452549, 0.04442261,
       0.01003174, 0.04508723, 0.00504459, 0.12302319, 0.00195218,
       0.0285837 , 0.02451965, 0.0167777 , 0.09793552, 0.11285928,
       0.02248784, 0.03657553, 0.03597172, 0.01557811, 0.01794333,
       0.03120094])

### Show the attributes that relevance rate is upper 0.06

In [53]:
importancias[importancias > 0.06]

array([0.06452549, 0.12302319, 0.09793552, 0.11285928])

In [71]:
import numpy as np

### Grab the index of more relevant attributes

In [57]:
indices = np.where(importancias > 0.06)

In [58]:
importancias[indices]

array([0.06452549, 0.12302319, 0.09793552, 0.11285928])

In [11]:
X_treinamento_3 = X_treinamento_2[:,[ 8, 13, 18, 19]]
X_teste_3 = X_teste_2[:,[ 8, 13, 18, 19]]

In [60]:
floresta = RandomForestClassifier(n_estimators = 100)
floresta.fit(X_treinamento_3, y_treinamento_2)

RandomForestClassifier()

In [61]:
previsoes = floresta.predict(X_teste_3)
confusao = confusion_matrix(y_teste, previsoes)
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.7153333333333334

### Try to another algorithm

In [12]:
from sklearn.svm import SVC

In [15]:
svm2 = SVC()
modelo = svm2.fit(X_treinamento_3, y_treinamento_2)
previsoes2 = modelo.predict(X_teste_3)
taxa_acerto = accuracy_score(y_teste_2, previsoes2)
taxa_acerto

0.8426666666666667

## Save the lastes model to reuse

In [1]:
import pickle

In [16]:
pickle.dump(modelo, open('app/modelo.sav','wb'))

## Run a teste with the save model 

### After use attribute selection I use columns [ 8, 13, 18, 19] to create X_treinamento_3 but I forgot to keep the columns names.

In [24]:
check_names = insurance[['GoodStudent', 'Age', 'SocioEcon',\
                          'RiskAversion', 'VehicleYear', 'ThisCarDam',\
                          'RuggedAuto', 'MakeModel', 'DrivQuality',\
                          'Mileage', 'Antilock', 'DrivingSkill',\
                          'SeniorTrain', 'ThisCarCost', 'Theft',\
                          'CarValue', 'HomeBase', 'AntiTheft',\
                          'PropCost', 'OtherCarCost', 'OtherCar',\
                          'MedCost', 'Cushioning', 'Airbag', 'ILiCost','DrivHist']]

In [23]:
check_names.columns[[ 8, 13, 18, 19]]

Index(['DrivQuality', 'ThisCarCost', 'PropCost', 'OtherCarCost'], dtype='object')

In [60]:
insurance['DrivQuality'].unique()

array(['Poor', 'Normal', 'Excellent'], dtype=object)

In [74]:
DrivQuality = check_names['DrivQuality'].values
DrivQuality = labelencoder.fit_transform(DrivQuality)
np.unique(DrivQuality)

array([0, 1, 2])

In [61]:
insurance['ThisCarCost'].unique()

array(['TenThou', 'Thousand', 'HundredThou', 'Million'], dtype=object)

In [75]:
ThisCarCost = check_names['ThisCarCost'].values
ThisCarCost = labelencoder.fit_transform(ThisCarCost)
np.unique(ThisCarCost)

array([0, 1, 2, 3])

In [62]:
insurance['PropCost'].unique()

array(['TenThou', 'Thousand', 'HundredThou', 'Million'], dtype=object)

In [77]:
PropCost = check_names['PropCost'].values
PropCost = labelencoder.fit_transform(PropCost)
np.unique(PropCost)

array([0, 1, 2, 3])

In [63]:
insurance['OtherCarCost'].unique()

array(['Thousand', 'HundredThou', 'TenThou'], dtype=object)

In [78]:
OtherCarCost = check_names['OtherCarCost'].values
OtherCarCost = labelencoder.fit_transform(OtherCarCost)
np.unique(OtherCarCost)

array([0, 1, 2])

In [80]:
modelo_salvo = pickle.load(open('app/modelo.sav','rb'))

In [83]:
test_record = [[1,3,1,0]]
test_record = np.asarray(test_record)

In [85]:
answer = modelo_salvo.predict(test_record)

In [86]:
print(answer)

['Moderate']
